import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Medal Count App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-fit mx-auto mt-12">{children}</div>
      </body>
    </html>
  );
}
